### ISSUE TITLE
Peer review by Ruizi Liu

### ISSUE THREAD

**Issue by RIRI0527** [khushaal-nandwani/predicting-lemurs#3]
#### **Summary**
The project aims to predict lemur species based on various features using machine learning models. The repository includes scripts, a README, and associated files but lacks critical components to ensure full reproducibility and transparency. The project demonstrates a solid foundation with room for improvement in documentation, data accessibility, and evaluation metrics.

**Strengths:**
- **Clear Objective:** The project’s purpose is well-defined, focusing on predicting lemur species using data-driven methods.
- **Repository Structure:** The repository is neatly organized into code and documentation folders, making navigation straightforward.
- **Model Usage:** Implements a machine learning-based approach, which aligns with the project’s goals.

**Critical Improvements Needed:**
- Include the dataset or clear instructions to access it.
- Add inline code documentation to enhance clarity.
- Provide model evaluation metrics such as accuracy, precision, recall, and confusion matrices.
- Include reproducibility details such as a `requirements.txt` file and setup instructions.

#### **Core Requirements**
1. **R/Python Cited**: **1/1**
   - Python is clearly cited in the README.
   - Use of libraries like `scikit-learn` and `pandas` is evident.

2. **Data Cited**: **0/1**
   - The dataset is not included or cited in the repository.
   - Suggestion: Provide a sample dataset or link to a publicly available source.

3. **Class Paper**: **1/1**
   - No indication that this is a class project.

4. **LLM Documentation**: **1/1**
   - The README includes an acknowledgment of the use of large language models (if applicable).

#### **Paper Sections**
1. **Title**: **2/2**
   - Informative and clearly conveys the project’s focus.

2. **Author, Date, and Repo**: **2/2**
   - Author details, submission date, and repository link are included.

3. **Abstract**: **3/4**
   - Summarizes the purpose but lacks details about specific findings.
   - Suggestion: Include a brief overview of model performance.

4. **Introduction**: **4/4**
   - Provides sufficient background and motivation for the project.

5. **Estimand**: **0/1**
   - The estimand is not explicitly defined.
   - Suggestion: Add a clear statement of the estimand, e.g., predicting the species of lemurs given input features.

6. **Data**: **6/10**
   - No dataset is included, and details about the data are minimal.
   - Suggestion: Provide a data dictionary, summary statistics, or sample observations.

7. **Measurement**: **3/4**
   - Variables are briefly mentioned but lack detailed explanations.

8. **Model**: **5/10**
   - The model implementation is adequate but lacks justification for variable inclusion or consideration of alternative models.
   - Suggestions:
     - Add a discussion on why specific features were selected.
     - Provide details on model limitations or scenarios where it may not perform well.

9. **Results**: **6/10**
   - No evaluation metrics or visualizations of results are provided.
   - Suggestion: Include metrics like accuracy, precision, recall, F1-score, and confusion matrices to validate the model.

10. **Discussion**: **6/10**
    - Highlights the potential applications but does not delve deeply into the implications or limitations.
    - Suggestion: Discuss real-world applications and areas for future improvement.

11. **Prose**: **5/6**
    - Clear and professional, with minor issues in technical descriptions.
    - Suggestion: Add more technical details in the prose for clarity.

12. **Cross-references**: **1/1**
    - Cross-references are minimal but functional.

13. **Captions**: **1/2**
    - Captions for figures and tables are insufficiently detailed.
    - Suggestion: Make captions informative enough to explain figures independently.

14. **Graphs/Tables**: **3/4**
    - Graphs and tables are present but limited in number and clarity.
    - Suggestion: Add more visuals to support the results.

15. **Surveys, Sampling, and Observational Data Appendix**: **0/10**
    - Not included.
    - Suggestion: Include an idealized survey or detailed explanation of the sampling process.

16. **Referencing**: **3/4**
    - The project cites Python libraries but lacks broader references to related work or external resources.

17. **Commits**: **2/2**
    - Multiple meaningful commits with clear messages.

18. **Sketches**: **2/2**
    - Not applicable but sufficient documentation is present.

19. **Simulation**: **2/4**
    - Simulations are limited and do not explore interaction effects.

20. **Tests**: **1/4**
    - No automated testing framework is included.
    - Suggestion: Use `pytest` to include unit tests for the codebase.

21. **Parquet**: **0/1**
    - Data is not saved as Parquet.
    - Suggestion: Use `arrow` to store processed data in an efficient format.

22. **Reproducible Workflow**: **2/4**
    - The lack of environment setup instructions and dataset hinders reproducibility.
    - Suggestion: Include a `requirements.txt` file and detailed setup guide.

23. **Enhancements**: **3/4**
    - No major enhancements like a model card or API are included.
    - Suggestion: Add a model card summarizing the model, data, and key results.

24. **Miscellaneous**: **2/3**
    - Repository could benefit from cleaning up unused files or folders.

### **Suggestions for Improvement**
1. **Data Accessibility**:
   - Include a dataset or clear instructions to obtain one.

2. **Model Evaluation**:
   - Provide performance metrics (e.g., accuracy, precision, recall) and visualizations (e.g., confusion matrix).

3. **Reproducibility**:
   - Add a `requirements.txt` file and a guide for setting up the environment.

4. **Appendix**:
   - Include an idealized survey or detailed explanation of the sampling process.

### **Overall Comments**
The "Predicting Lemurs" project shows strong potential but requires improvements in documentation, data accessibility, and evaluation details to reach its full potential. Great foundation to build upon!

**Comment by khushaal-nandwani** [comment]
Done, thank you:)
